name: Build and upload nightly ipa

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'
      - name: Get commit SHA
        id: commitinfo
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build
        run: xcodebuild -scheme "GenshinPizzaHelper" -configuration Release archive -archivePath build/GenshinPizzaHelper.xcarchive CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Package ipa
        run: |
          mkdir Payload
          cp -r build/GenshinPizzaHelper.xcarchive/Products/Applications/&#x62ab;&#x8428;&#x5c0f;&#x52a9;&#x624b;.app Payload
          zip -r GenshinPizzaHelper-iOS_nightly-${{ steps.commitinfo.outputs.sha_short }}.ipa Payload
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GenshinPizzaHelper-iOS_nightly-${{ steps.commitinfo.outputs.sha_short }}.ipa
          path: GenshinPizzaHelper-iOS_nightly-${{ steps.commitinfo.outputs.sha_short }}.ipa
          if-no-files-found: error