name: Build and upload nightly ipa

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'
      - name: Get commit SHA
        id: commitinfo
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build
        env:
          SCHEME_NAME: "GenshinPizzaHelper"
        run: |
          xcodebuild -scheme "$SCHEME_NAME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            archive -archivePath build/GenshinPizzaHelper.xcarchive \
            CODE_SIGN_IDENTITY= \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Package ipa
        run: |
          mkdir Payload
          cp -r build/GenshinPizzaHelper.xcarchive/Products/Applications/披萨小助手.app Payload
          zip -r GenshinPizzaHelper-iOS_nightly-${{ steps.commitinfo.outputs.sha_short }}.ipa Payload
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GenshinPizzaHelper-iOS_nightly-${{ steps.commitinfo.outputs.sha_short }}.ipa
          path: GenshinPizzaHelper-iOS_nightly-${{ steps.commitinfo.outputs.sha_short }}.ipa
          if-no-files-found: error