name: Build and upload nightly ipa

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'
          
      - name: Get commit SHA
        id: commitinfo
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
      - name: Clean Build Directory
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          rm -rf build
          
      - name: Archive App
        env:
          SCHEME_NAME: "GenshinPizzaHelper"
        run: |
          xcodebuild clean archive \
            -scheme "$SCHEME_NAME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/GenshinPizzaHelper.xcarchive \
            DEVELOPMENT_TEAM="" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_BITCODE=NO \
            COMPILER_INDEX_STORE_ENABLE=NO \
            ONLY_ACTIVE_ARCH=NO
            
      - name: Export IPA
        run: |
          cat << EOF > exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>compileBitcode</key>
              <false/>
              <key>stripSwiftSymbols</key>
              <false/>
          </dict>
          </plist>
          EOF
          
          xcodebuild -exportArchive \
            -archivePath build/GenshinPizzaHelper.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
            
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GenshinPizzaHelper-iOS_nightly-${{ steps.commitinfo.outputs.sha_short }}.ipa
          path: build/ipa/*.ipa
          if-no-files-found: error